-- mod-version:3
local syntax = require "core.syntax"

syntax.add {
  name = "Crystal",
  files = { "%.cr$" },
  headers = "^#!.*[ /]crystal",
  comment = "#",
  patterns = {
    { pattern = { '"', '"', '\\' },      type = "string"   },
    { pattern = { "'", "'"},             type = "string"   },
    { pattern = "-?0x%x+",               type = "number"   },
    { pattern = "%#.-\n",                type = "comment"  },
    { pattern = " : [%w_| :]*",          type = "comment"  },
    { pattern = "-?%d+[%d%.eE]*%f[^eE]", type = "number"   },
    { pattern = "-?%.?%d+f?",            type = "number"   },
    { pattern = "[%+%-=/%*%^%%<>!~|&]",  type = "operator" },
    { pattern = "[%a_][%w_]*%f[(?]",     type = "function" },
    { pattern = "%.[%a_][%w_]*%f[(%s]",  type = "function" },
    { pattern = "@?@[%a_][%w_]*",        type = "keyword2" }, 
    { pattern = ":-[%u_][%u%d_]*%f[^%w]",type = "keyword2" }, --constants
    { pattern = "::[%w_]*",              type = "symbol"   },
    { pattern = ":[%w_]*",               type = "symbol"   },
    { pattern = "[%a_][%w_]*:[^:]",      type = "keyword2" },
    { pattern = "[%a_][%w_]*",           type = "symbol"   },
  },
  symbols = {
    ["__ENCODING__"] = "keyword",
    ["__FILE__"]     = "keyword",
    ["__LINE__"]     = "keyword",
    ["abstract"]     = "keyword",
    ["alias"]        = "keyword",
    ["annotation"]   = "keyword2",
    ["BEGIN"]        = "keyword",
    ["begin"]        = "keyword",
    ["break"]        = "keyword",
    ["case"]         = "keyword",
    ["class"]        = "keyword",
    ["def"]          = "keyword",
    ["defined?"]     = "keyword",
    ["do"]           = "keyword",
    ["else"]         = "keyword",
    ["elsif"]        = "keyword",
    ["END"]          = "keyword",
    ["end"]          = "keyword",
    ["ensure"]       = "keyword",
    ["enum"]         = "keyword2",
    ["extend"]       = "keyword",
    ["false"]        = "literal",
    ["fun"]          = "keyword",
    ["if"]           = "keyword",
    ["in"]           = "keyword",
    ["include"]      = "keyword",
    ["module"]       = "keyword",
    ["next"]         = "keyword",
    ["nil"]          = "literal",
    ["out"]          = "function",
    ["private"]      = "keyword2",
    ["puts"]         = "function",
    ["p!"]           = "function",  
    ["require"]      = "keyword",
    ["rescue"]       = "keyword",
    ["responds_to?"] = "function",
    ["Void"]         = "literal",
    ["return"]       = "keyword2",
    ["self"]         = "keyword2",
    ["super"]        = "keyword2",
    ["then"]         = "keyword",
    ["true"]         = "literal",
    ["undef"]        = "keyword",
    ["unless"]       = "keyword",
    ["until"]        = "keyword",
    ["when"]         = "keyword",
    ["while"]        = "keyword",
    ["yield"]        = "keyword"
  },
}
