-- mod-version:2 -- lite-xl 2.0
local syntax = require "core.syntax"

syntax.add {
  name = "Crystal",
  files = { "%.cr" },
  headers = "^#!.*[ /]crystal",
  comment = "#",
  patterns = {
    { pattern = { '"', '"', '\\' },     type = "string"   },
    { pattern = { "'", "'", '\\' },     type = "string"   },
    { pattern = "-?0x%x+",              type = "number"   },
    { pattern = "%#.-\n",               type = "comment"  },
    { pattern = "-?%d+[%d%.eE]*f?",     type = "number"   },
    { pattern = "-?%.?%d+f?",           type = "number"   },
    { pattern = "[%+%-=/%*%^%%<>!~|&]", type = "operator" },
    { pattern = "[%a_][%w_]*%f[(]",     type = "function" },
    { pattern = "@?@[%a_][%w_]*",       type = "keyword2" },
    { pattern = "::[%w_]*",             type = "symbol" },
    { pattern = ":[%w_]*",              type = "keyword2" },
    { pattern = "[%a_][%w_]*:[^:]",     type = "keyword2" },
    { pattern = "[%a_][%w_]*",          type = "symbol"   },
  },
  symbols = {
    ["__ENCODING__"]        = "keyword",
    ["__FILE__"]            = "keyword",
    ["__LINE__"]            = "keyword",
    ["alias"]               = "keyword",
    ["BEGIN"]               = "keyword",
    ["begin"]               = "keyword",
    ["break"]               = "keyword",
    ["case"]                = "keyword",
    ["class"]               = "keyword",
    ["def"]                 = "keyword",
    ["defined?"]            = "keyword",
    ["do"]                  = "keyword",
    ["else"]                = "keyword",
    ["elsif"]               = "keyword",
    ["end"]                 = "literal",
    ["END"]                 = "keyword",
    ["end"]                 = "keyword",
    ["ensure"]              = "keyword",
    ["extend"]              = "keyword",
    ["false"]               = "literal",
    ["for"]                 = "keyword",
    ["if"]                  = "keyword",
    ["in"]                  = "keyword",
    ["include"]             = "keyword",
    ["module"]              = "keyword",
    ["next"]                = "keyword",
    ["nil"]                 = "literal",
    ["not"]                 = "keyword",
    ["private"]             = "keyword",
    ["redo"]                = "keyword",
    ["require"]             = "keyword",
    ["require_dependency"]  = "keyword",
    ["rescue"]              = "keyword",
    ["retry"]               = "keyword",
    ["return"]              = "keyword",
    ["self"]                = "keyword",
    ["super"]               = "keyword",
    ["then"]                = "keyword",
    ["true"]                = "literal",
    ["true"]                = "keyword",
    ["undef"]               = "keyword",
    ["unless"]              = "keyword",
    ["until"]               = "keyword",
    ["when"]                = "keyword",
    ["while"]               = "keyword",
    ["yield"]               = "keyword"
  },
}

